* Strict categories

Say a category C is strictly associative and unital if its
associativity and unit laws follow by reflexivity. We call such a
category a strict category. Note that this is a metatheoretic
property, it cannot be stated internally (though maybe with 2LTT?).

Examples:
1. The category Set
2. If C is a strict cat and I a type, the power category C^I

Non-examples:
1. The free category
2. Generally any quotient construction
3. The functor category C^D where C is a strict cat

Strict categories are much more convenient as it means that the
*typechecker* can *unify* expressions that are equivalent modulo
associativity and unit!

Wouldn't it be nice if the typechecker could do that for all
categories? Well we can develop a lemma that will get us there.

First, we need some help: getting Agda to solve an equation
definitionally in an arbitrary category won't ever work. Instead,
we'll ask that our input be given to us as a syntactic expression
involving compositions and identities, rather than as a morphism in
ð“’. That is, our input will be not a morphism in ð“’, but rather in ð“¦ ð“’ =
F U ð“’ a *free category* on the *underlying graph* of ð“’. This would be
tedious to require the user to do by hand, but we can use some Agda
macros to parse a goal into such an expression.

Though the free category is a 2-categorical universal property andasy
therefore defined up to equivalence of categories, we are concerned
with *definitional* equalities here and so we need a presentation of
the free category that satisfies some nice definitional properties.

The universal property of the free category FG on a graph G is a
1. A homomorphism Î· : G â†’ UFG
2. Such that for any Ä± : G â†’ U ð““ there exists a unique E[Ä±] : F G â†’ ð““ such that U(E[Ä±]) âˆ˜ Î· â‰¡ Ä±.

The intuition is that Î· is the inclusion of generators: it maps the
nodes of G to an object of FG and the edges of G to morphisms in
FG. Then Ä± is an interpretation of the generators in another category,
and for the free category this uniquely defines a functor that extends
the interpretation Ä±.

For our purposes we will require a further definitional property of the free category, that for any Ä±:
1. Functoriality (preservation of composition, identity) is *definitional*
2. Given Ä±, the equality E[Ä±] âˆ˜ Î· â‰¡ Ä± is *definitional*

For (1) we say that E[Ä±] is *definitionally* functorial and (2) we say
that E[Ä±] *definitionally* maps the generators according to Ä±. Why is
this important? Well remember for our purposes we have some actual
equation e1 â‰¡ e2 in ð“’ which is written as a bunch of compositions in
ð“’. We will then solve an equation e1' â‰¡ e2' in FU ð“’ and want to use
the functor Îµ : FUð“’ â†’ ð“’ to map this to our original equation. Well it
is very important that Îµ map this to *definitionally* the equation e1
â‰¡ e2 or we'll just be stuck with another tedious proof.

It's worth considering why this part is non-trivial: there are (very
useful) presentations of the free category that do not satisfy these
definitional properties. The most common one is to define the free
category to have objects be the nodes of G and have morphisms be the
*paths* in the graph, i.e., inductively generated from id and
composition of an edge with a path. This is a normalized form and can
be used for the next part of the solver if desired, but it cannot be
used here yet, as it is not *definitionally* functorial and does not
*definitionally* preserve Ä±:
1. It does preserve id definitionally, but given an expression (id o
   f), in this normalized free cat this is definitionally equal to f,
   and so we will not have that E[Ä±] (id âˆ˜ f) is definitionally equal
   to E[Ä±](id) âˆ˜ E[Ä±] f = id âˆ˜ E[Ä±] f
2. It does not preserve generators definitionally. A generator will be
   a singleton path (Î· f âˆ˜ id) and this will be mapped to E[Ä±] f âˆ˜ id
   which is not generally definitionally equal to E[Ä±] f.

However for the free category at least, it is easy to construct such a
definitionally well behaved free category as a HIT (in fact a QIT):
just inductively add in cases for generators, id, composition and the
equations/isSet. Proving this is the free category is pretty much
tautological, so we call it the tautological free category.

But now we have reduced our original problem of solving an equation e1
â‰¡ e2 in ð“’ with a problem of solving a related equation e1' â‰¡ e2' in ð“¦
ð“’ = FUð“’. So how do we solve that equation? What we want is to define a
third category ð“¦ð“’! with a functor ð“˜ : ð“¦ ð“’ â†’ ð“¦ð“’! which has the
following nice properties:
1. ð“˜ is faithful: if ð“˜ âŸª e1' âŸ« â‰¡ ð“˜ âŸª e2' âŸ« then e1' â‰¡ e2'
2. if e1' â‰¡ e2' in ð“¦ð“’ then ð“˜ âŸª e1' âŸ« â‰¡ ð“˜ âŸª e2' âŸ« *definitionally*

One solution, the "syntactic" approach, is to take ð“¦ð“’! to be the free
category defined with morphisms as paths above. Because this is the
free category, we can define a functor ð“˜ : ð“¦ ð“’ â†’ F_path ð“’ that is not
just faithful but an equivalence of categories. And by sending
generators to generators, we can get (for closed expressions e1', e2'
at least) that property (2) holds as well. This works perfectly fine
but it's a bit tedious to prove, there is a surprising trick that
works even more easily.

If I give you a category ð“’ and ask you if you know of any nice
categories it embeds into with a faithful functor, your first guess
should probably be the presheaf category on ð“’, with the Yoneda
embedding. In fact this almost works, we can try using ð“¦ð“’! = Presheaf
(ð“¦ ð“’), but we don't *quite* have the second property above, because
morphisms in the presheaf category are *natural* transformations and
so morphisms come with a *proof* of equality. And though equality of
morphisms in a category is a proposition, it is only a *path-wise*
proposition, not a *definitional* proposition. Note that this would
work with definitional proof irrelevance though! However we can get
away with a slightly different construction. To get rid of the proofs,
we can use instead of natural transformations, "possibly unnatural
transformations", i.e., families of morphisms. The most natural place
for such morphisms to live is in what I call the "power category" of
Set by a type X. Then instead of using presheaves on ð“¦ð“’, we can take
the power of Set raised to the underlying type of objects of ð“¦ð“’. This
is a bit less familiar than the presheaf category but it is closely
related: we still get a variant of the Yoneda embedding, but we have
only a *faithful* functor rather than a *fully faithful*
functor. Fortunately a faithful functor is all we require. And this
category has a very nice property: it is *definitionally* unital and
associative, because composition is just composition of Agda
functions, which is definitionally unital and associative because
Agda's definitional equality includes Î²Î· equality of functions. Then
if only ð“˜ were definitionally functorial, we would have property (2)
because we would map compositions in ð“¦ ð“’ to compositions in ð“˜ and Agda
would be able to solve them.

Unfortunately it's not actually the case that this "pseudo-Yoneda"
embedding has property 2. But the nice thing about this free category
is that we can use its UMP to make an equivalent functor that is! That
is, given the pseudo Yoneda embedding ð“˜ : ð“¦ ð“’ â†’ Pow (ð“¦ ð“’ .ob), we can
reconstruct it as the definitionally functorial E[U ð“˜ âˆ˜ Î·], which we
can prove is path equal to ð“˜ because they agree (definitionally) on
generators. 

Let's look at an example to see how this all fits together: Consider an equality we'd like to prove in a category ð“’:

    id âˆ˜ ((g âˆ˜ id) âˆ˜ f) âˆ˜ id â‰¡ g âˆ˜ (id âˆ˜ f)

These are clearly equal up to associativity and unit, but proving this
by applying associativities and units explicitly is a chore.

First, we write this as an expression in the free category on ð“’:

    id âˆ˜ ((Î· g âˆ˜ id) âˆ˜ Î· f) âˆ˜ id â‰¡ Î· g âˆ˜ (id âˆ˜ Î· f)

Not so different actually... But now, we apply the functor ð“˜' := E[U ð“˜ âˆ˜ Î·]
to the right side:
    ð“˜' âŸª Î· g âˆ˜ (id âˆ˜ Î· f) âŸ«
    = Î» x â†’ (ð“˜' âŸª Î· g âŸ« âˆ˜Set (ð“˜' âŸª id âˆ˜ Î· f âŸ«)) x
    = Î» x â†’ ((Î» x â†’ Î· g âˆ˜ x) âˆ˜Set ((Î» x â†’ x) âˆ˜ (Î» x â†’ Î· f âˆ˜ x))) x
    = (Î» x â†’ Î· g âˆ˜ x) ((Î» x â†’ x) ((Î» x â†’ Î· f âˆ˜ x) x))
    = (Î» x â†’ Î· g âˆ˜ x) ((Î» x â†’ x) (Î· f âˆ˜ x))
    = (Î» x â†’ Î· g âˆ˜ x) (Î· f âˆ˜ x)
    = Î» x â†’ Î· g âˆ˜ (Î· f âˆ˜ x)

Since the identity morphism gets mapped to the identity function, and
composition gets mapped to composition of functions, they simply get
"evaluated away" and we get a fully right associated form. If we apply
the same thing to the left then we can derive a definitional equality
to the same form. Then because ð“˜ â‰¡ ð“˜' and ð“˜ is faithful, we get that
ð“˜' is faithful and therefore the equality

    id âˆ˜ ((Î· g âˆ˜ id) âˆ˜ Î· f) âˆ˜ id â‰¡ Î· g âˆ˜ (id âˆ˜ Î· f)

holds in ð“¦ ð“’. Then applying the functor Îµ : ð“¦ ð“’ â†’ ð“’, by preservation
of paths and nice definitional behavior of Îµ we get the original equality:

    id âˆ˜ ((g âˆ˜ id) âˆ˜ f) âˆ˜ id â‰¡ g âˆ˜ (id âˆ˜ f)

** Footnote on the power category

The power category is actually a very interesting category: it is
equivalent to a presheaf category over the discrete category on the
type of objects, and there is a faithful forgetful functor

   U : Presheaf ð“’ â†’ Pow ð“’

that has a left and right adjoints which "build in functoriality" in
dual ways:

    (L P) c = coend_c' ð“’ [ c , c' ] Ã— P c'
    (R P) c = end_c' ð“’ [ c' , c ] â†’ P c'

Which look *exactly* like the coYoneda and Yoneda lemmas respectively:
the presheaves are exactly the families of sets equipped with a proof
that the (co)Yoneda lemma "is true".

Let Pow ð“’ be the presheaf category on the underlying type of objects
and Psh ð“’ be the presheaf category on ð“’.

Then there is a forgetful functor U : Psh ð“’ â†’ Pow ð“’, which has a right
adjoint R given by (R Q) c = âˆ€ c'. ð“’ [ c' , c ] â†’ P c'

P -> R Q =~ U P â†’ Q

Î· : P >--> R U P
Îµ : U (R P) -->> P


(TODO: details)
