* Strict categories

Say a category C is strictly associative and unital if its
associativity and unit laws follow by reflexivity. We call such a
category a strict category. Note that this is a metatheoretic
property, it cannot be stated internally (though maybe with 2LTT?).

Examples:
1. The category Set
2. If C is a strict cat and I a type, the power category C^I

Non-examples:
1. The free category
2. Generally any quotient construction
3. The functor category C^D where C is a strict cat

Strict categories are much more convenient as it means that the
*typechecker* can *unify* expressions that are equivalent modulo
associativity and unit!

Wouldn't it be nice if the typechecker could do that for all
categories? Well we can develop a lemma that will get us there.

Construction:
Given any category ğ“’ we construct a strict category ğ“’! and a faithful functor ğ“˜ : ğ“’ â†’ ğ“’!

Define ğ“’! as Set^|ğ“’ .ob|, and define ğ“˜ analogous to the Yoneda
embedding. This is faithful via a similar proof as the Yoneda
lemma.

Unlike the Yoneda embedding, this functor is not generally full, but
fullness is not needed for our purposes here.

How can we take advantage of this theorem? Say we have defined two
parallel morphisms f , g in ğ“’ and we want to prove they are equal, and
they *would* be definitionally equal if ğ“’ were a definitional
category. We might try to use the faihful functor ğ“˜ above to map them
into ğ“’! and then hope that it works automatically, but alas, the
functor ğ“˜ is not *definitionally functorial*, so this would amount to
another tedious proof.

Well before we were able to construct a definitional variant of the
category ğ“’ so can we define a definitional variant of ğ“˜ to? Sort of!
What we can do is define another (non-definitional) category ğ“¦ ğ“’ with
1. A *definitional* functor Îµ : ğ“¦ ğ“’ â†’ ğ“’
2. A *definitional* functor Îµ! : ğ“¦ ğ“’ â†’ ğ“’!
3. With a *propositional* equality ğ“˜ âˆ˜ Îµ â‰¡ Îµ!

How does this help us? So far ğ“¦ ğ“’ could be the empty
category. Intuitively, we need that Îµ is a *full* functor, so that our
parallel morphisms f and g can be defined in ğ“¦ ğ“’. In fact Îµ is (even
definitionally) full, but this is not as helpful as it sounds, as the
proof of fullness is not functorial. We have to give up something, so
what we will say is that instead of writing f and g, morphisms in ğ“’,
you need to write instead parallel morphisms fW and gW in ğ“¦ ğ“’ such
that Îµ (fW) = f and Îµ (gW) = g *definitionally* but whatever
compositions/identities we need re-written are compositions in ğ“¦
ğ“’. That way, Îµ! will definitionally preserve the compositions, and we
will get that Îµ! (fW) is *definitionally* equal to Îµ! (gW), so the
type checker can prove it for us. Then by (3) we can conclude that f
and g are *propositionally* equal, which is what we desired.

What is the ğ“¦ ğ“’ we want? It is the *free category* on the underlying
graph of ğ“’. This category has the same objects as ğ“’ and its morphisms
are quotiented "category expressions", we throw in all of the
morphisms of ğ“’ but also new identities and new composites. Note that
while it looks like we can define a functor ğ“’ â†’ ğ“¦ ğ“’ by sending every
morphism to its inclusion in expressions, but this does not preserve
identity or composition, instead this is only a *graph homomorphism* U
ğ“’ â†’ U (ğ“¦ ğ“’). We call this homomorphism Î·.

This free category has a universal property: given any graph
homomorphism Ä± : U ğ“’ â†’ U ğ““, we can define a functor Ind[Ä±] : ğ“¦ ğ“’ â†’ ğ““ such that
1. Ind[Ä±] is definitionally functorial
2. U(Ind[Ä±]) âˆ˜ Î· is definitionally equal to Ä±
3. If U F âˆ˜ Î· â‰¡ Ä± then F â‰¡ Ind[Ä±] (note these are identifications, not definitional equalities)

Then we can define
1. Îµ = Ind[id]
2. Îµ! = Ind[ğ“˜]
3. ğ“˜ âˆ˜ Îµ â‰¡ Îµ! means ğ“˜ âˆ˜ Îµ â‰¡ Ind[ğ“˜] which by (3) STS U(ğ“˜ âˆ˜ Îµ) âˆ˜ Î· â‰¡ ğ“˜
   which follows because

   U(ğ“˜ âˆ˜ Îµ) âˆ˜ Î· = U ğ“˜ âˆ˜ (UÎµ o Î·) â‰¡ U ğ“˜

So there is one last bit of tedium here: we must take f and g and
rewrite them as fW and gW where we replace compositions in ğ“’ with
compositions in ğ“¦ğ“’. This *cannot* be done within the theory, as it
does not respect definitional equality! So this is a meta-operation,
and so we can either perform it manually using some convenient
notation or automate it with a meta-program. Fortunately in this case
the meta-program is fairly easy to write: we essentially parse an Agda
term into a ğ“¦ ğ“’ morphism.

